; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
Update=1000

[Metadata]
    Name=MARATERM_SYSTEM_MONITOR.ini
    Author=crimsonHecatomb
    Description=Displays basic system stats.
    License=Creative Commons BY-NC-SA 3.0
    Version=1.0.0

[Variables]
    ; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
    ; Base aesthetics
        ; Floating widgets
            BackgroundMode=2
            WIDGBackground=0, 0, 0, 1 ; Almost Transparent, helps with hitbox
            WIDGFont=Monaco

        ; The colors
            ColorTYC=255, 0, 0, 255    ; Red
            ColorDUR=0, 255, 0, 255    ; Green
            ColorLEE=0, 0, 255, 255    ; Blue
            ColorTERM=255, 255, 255, 255   ; White

        ; Dimmed background colors for the empty part of the bars
            DimTYC=50, 0, 0, 255   ; Dimmed Red
            DimDUR=0, 50, 0, 255   ; Dimmed Green
            DimLEE=0, 0, 50, 255   ; Dimmed Blue

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

    [StyleTextCenter]
        FontFace=#WIDGFont#
        FontSize=12
        AntiAlias=0
        StringAlign=Center

    [StyleBar]
        W=40
        H=225
        AntiAlias=0
        BarOrientation=VERTICAL

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

    [MeasureCPU]
    ; This measure returns the average CPU load between all cores.
        Measure=CPU
        Processor=0

    [measureRAM]
    ; Returns the amount of RAM used in bytes.
        Measure=PhysicalMemory
        UpdateDivider=20
    ; UpdateDivider sets the rate at which the value of the measure is updated. It is
    ; calculated as follows: UpdateDivider x Update. In this case, Update is set to
    ; 1000 milliseconds (in the [Rainmeter] section). 1000 x 20 =20000 ms or 20 seconds.

    [measureSWAP]
    ; Returns the amount of SWAP (pagefile) used in bytes.
        Measure=SwapMemory
        UpdateDivider=20

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

    ; The Background Box (Invisible but still bounding)
    [MeterBackground]
        Meter=Image
        SolidColor=#WIDGBackground#
        W=220
        H=335

    ; Widget Name
    [MeterSystemLabel]
        Meter=String
        MeterStyle=StyleTextCenter
        X=110
        Y=295
        FontSize=18
        FontColor=#ColorTERM#
        Text="SYSTEM STATUS"

    ; The Vertical Bars
    [MeterCPUBar]
        Meter=Bar
        MeterStyle=StyleBar
        MeasureName=MeasureCPU
        BarColor=#ColorDUR#
        SolidColor=#DimDUR#
        X=20
        Y=20

    [MeterRAMBar]
        Meter=Bar
        MeterStyle=StyleBar
        MeasureName=MeasureRAM
        BarColor=#ColorTYC#
        SolidColor=#DimTYC#
        X=90
        Y=20

    [MeterSWPBar]
        Meter=Bar
        MeterStyle=StyleBar
        MeasureName=measureSWAP
        BarColor=#ColorLEE#
        SolidColor=#DimLEE#
        X=160
        Y=20

    ; The Labels and Percentages
    ; '#CRLF#' is Rainmeter's code for a line break.
    [MeterCPULabel]
        Meter=String
        MeterStyle=StyleTextCenter
        MeasureName=MeasureCPU
        X=40
        Y=250
        FontColor=#ColorDUR#
        Text="CPU#CRLF#%1%"

    [MeterRAMLabel]
        Meter=String
        MeterStyle=StyleTextCenter
        MeasureName=MeasureRAM
        X=110
        Y=250
        FontColor=#ColorTYC#
        Text="RAM#CRLF#%1%"
        Percentual=1

    [MeterSWPLabel]
        Meter=String
        MeterStyle=StyleTextCenter
        MeasureName=measureSWAP
        X=180
        Y=250
        FontColor=#ColorLEE#
        Text="SWP#CRLF#%1%"
        Percentual=1
        