; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
Update=1000

[Metadata]
Name=MARATERM_COMMAND_OPERATIONS_MODULE.ini
Author=crimsonHecatomb
Description=Dock with Network status, audio, search, Discord, start menu and terminal access.
License=Creative Commons BY-NC-SA 3.0
Version=1.0.0

[Variables]
    ; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
    ; Base aesthetics
        ; Top and bottom bars
            BARBackground=39, 1, 0, 255
            BARFontColor=255, 0, 0, 255
            BARFont=Courier New
            BARFontSize=40

        ; Change these to shift all elements at once
            MarginTop=13
            MarginLeft=15
            MarginRight=15
            Spacing=255

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

    [StyleTextFull]
        FontFace=#BARFont#
        FontSize=#BARFontSize#
        FontColor=#BARFontColor#
        AntiAlias=0

    [StyleTextBreak]
        FontFace=#BARFont#
        FontSize=20
        FontColor=#BARFontColor#
        AntiAlias=0

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

    [MeasureSearchInput]
    ; The InputText plugin has special powers: it allows user input.
    ; However, it's not the easiest way to start learning Rainmeter. Get a
    ; hold of the basics, and then check out the manual entry for InputText.
        Measure=Plugin
        Plugin=InputText
        SolidColor=#BARBackground#
        X=([MeterSearchButton:X] + 35)
        Y=(#MarginTop# + 1)
        W=210
        H=80
        FontFace=#BARFont#
        FontSize=#BARFontSize#
        FontColor=255, 255, 255, 255
        Command1=["https://www.duckduckgo.com/?q=$UserInput$"]
    ; If you want to change your preferred search engine you must look at how it parses requests, I chose DDG because of course I did.
        FocusDismiss=1
        AntiAlias=0
        
    ; The following measures return data related to your audio equipment, it was a mess to get working.
    ; For more information, go here: https://docs.rainmeter.net/manual/plugins/win7audio/
    [MeasureVolume]
        Measure=Plugin
        Plugin=Win7AudioPlugin

    [MeasureVolumeMath]
        Measure=Calc
        Formula=MeasureVolume
        Substitute="-1":"OFFLINE"

    [MeasureAudioDevice]
        Measure=Plugin
        Plugin=Win7AudioPlugin
        SysInfoType=DEVICE_NAME

    [MeasureInternet]
    ; This measure returns the state of your network. If you're a beginner with
    ; Rainmeter, take a look at some of the other illustro skins before modifying this one.
    ; For more information, go here: https://docs.rainmeter.net/manual/measures/sysinfo/
        Measure=Plugin
        Plugin=SysInfo
        SysInfoType=INTERNET_CONNECTIVITY
        Substitute="-1":"OFFLINE","1":"ONLINE"

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

    ; The Background Box
    [MeterBackground]
        Meter=Image
        SolidColor=#BARBackground#
        W=#SCREENAREAWIDTH#
        H=84

    ; --- APP LAUNCHERS (Left Side) ---
    [MeterStart]
        Meter=String
        MeterStyle=StyleTextFull
        X=#MarginLeft#
        Y=#MarginTop#
        Text="[START]"
        LeftMouseUpAction=["#@#StartMenu.vbs"]

    [MeterVC]
        Meter=String
        MeterStyle=StyleTextFull
        X=([MeterStart:X] + #Spacing#)
        Y=#MarginTop#
        Text="[COMMS]"
        LeftMouseUpAction=["%LocalAppData%\vesktop\vesktop.exe"]
        ; Why Vesktop and not Discord? Because Vesktop lets you use themes on Discord and you can infer the rest.

    [MeterBrowser]
        Meter=String
        MeterStyle=StyleTextFull
        X=([MeterVC:X] + #Spacing#)
        Y=#MarginTop#
        Text="[BROWSE]"
        LeftMouseUpAction=["https://tauceti.world/explorer"]
        DynamicVariables=1

    ; --- SEARCH ---
    [MeterSearchButton]
        Meter=String
        MeterStyle=StyleTextFull
        X=([MeterBrowser:X] + #Spacing# + 35)
        Y=#MarginTop#
        Text=">SEARCH"
        LeftMouseUpAction=[!CommandMeasure "MeasureSearchInput" "ExecuteBatch 1"]
        DynamicVariables=1

    ; --- SYSTEM INFO (Right Side) ---
    [MeterVolumeLabel]
        Meter=String
        MeterStyle=StyleTextFull
        MeasureName=MeasureVolumeMath
        X=([MeterSearchButton:X] + 260)
        Y=#MarginTop#
        Text="VOL:%1%"
        ; Scroll wheel changes volume
        MouseScrollUpAction=[!CommandMeasure "MeasureVolume" "ChangeVolume +5"][!Update]
        MouseScrollDownAction=[!CommandMeasure "MeasureVolume" "ChangeVolume -5"][!Update]
        LeftMouseUpAction=[!CommandMeasure "MeasureVolume" "ToggleMute"][!Update]
        DynamicVariables=1

    ; Audio Device Toggle (Scroll to switch input)
    [MeterAudioDevice]
        Meter=String
        MeterStyle=StyleTextBreak
        MeasureName=MeasureAudioDevice
        X=([MeterVolumeLabel:X] + 250)
        Y=#MarginTop#
        W=150
        Text="OUT:#CRLF#%1"
        ClipString=1
        MouseScrollUpAction=[!CommandMeasure "MeasureVolume" "TogglePrevious"][!Update]
        MouseScrollDownAction=[!CommandMeasure "MeasureVolume" "ToggleNext"][!Update]
        LeftMouseUpAction=[!CommandMeasure "MeasureVolume" "ToggleMute"][!Update]
        DynamicVariables=1

    [MeterInternetLabel]
        Meter=String
        MeterStyle=StyleTextFull
        MeasureName=MeasureInternet
        X=([MeterAudioDevice:X] + 190)
        Y=#MarginTop#
        Text="NET: %1"
        DynamicVariables=1