; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
Update=1000

[Metadata]
    Name=MARATERM_STORAGE_MONITOR.ini
    Author=crimsonHecatomb
    Description=Displays disk usage.
    License=Creative Commons BY-NC-SA 3.0
    Version=1.0.0

[Variables]
    ; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
    ; Base aesthetics
        Disk1=C:
        
        ; Floating widgets
            BackgroundMode=2
            WIDGBackground=0, 0, 0, 1 ; Almost Transparent, helps with hitbox
            WIDGFont=Monaco

        ; The colors
            ColorTYC=255, 0, 0, 255    ; Red
            ColorDUR=0, 255, 0, 255    ; Green
            ColorLEE=0, 0, 255, 255    ; Blue
            ColorTERM=255, 255, 255, 255   ; White

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

    [StyleTextCenter]
        FontFace=#WIDGFont#
        FontSize=12
        AntiAlias=0
        StringAlign=Center

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

    [measureTotalDisk]
    ; This measure returns the total disk space
        Measure=FreeDiskSpace
        Drive=#Disk1#
        Total=1
        UpdateDivider=120

    [measureUsedDisk]
    ; Returns inverted value of free disk space (i.e. used disk space)
        Measure=FreeDiskSpace
        Drive=#Disk1#
        InvertMeasure=1
        Percentual=1
        UpdateDivider=120

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

    [MeterRadarBackground]
        Meter=Shape
        Shape=Ellipse 100,100,95 | Fill Color 0,0,0,150 | StrokeWidth 5 | Stroke Color #ColorTYC#
        X=0
        Y=0
        LeftMouseUpAction=["#Disk1#\"]
        ToolTipText="Open #Disk1#"

    [MeterRadarEmpty]
        Meter=Roundline
        X=0
        Y=0
        W=200
        H=200
        LineLength=85
        LineStart=50
        StartAngle=(-PI/2)
        RotationAngle=(2*PI)
        LineColor=#ColorLEE#
        Solid=1
        AntiAlias=0
        LeftMouseUpAction=["#Disk1#\"]

    [MeterRadarFill]
        Meter=Roundline
        MeasureName=measureUsedDisk
        X=0
        Y=0
        W=200
        H=200
        LineLength=85
        LineStart=50
        StartAngle=(-PI/2)
        RotationAngle=(2*PI)
        LineColor=#ColorDUR#
        Solid=1
        AntiAlias=0
        Percentual=1
        LeftMouseUpAction=["#Disk1#\"]

    [meterValueDisk]
        Meter=String
        MeterStyle=StyleTextCenter
        MeasureName=measureUsedDisk
        MeasureName2=measureTotalDisk
        X=100
        Y=210
        FontColor=#ColorTERM#
        Text=%1B / %2B
        NumOfDecimals=1
        AutoScale=1

    [meterTitle]
        Meter=String
        MeterStyle=StyleTextCenter
        X=100
        Y=8R
        FontSize=14
        FontWeight=600
        Text=STORAGE
        FontColor=#ColorTERM#