; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
Update=1000

[Metadata]
    Name=MARATERM_INCOMING_MESSAGE.ini
    Author=crimsonHecatomb
    Description=Displays basic system stats.
    License=Creative Commons BY-NC-SA 3.0
    Version=1.0.0

[Variables]
    ; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
    ; Base aesthetics
        ; Floating widgets
            BackgroundMode=2
            WIDGBackground=0, 0, 0, 1 ; Almost Transparent, helps with hitbox
            WIDGFont=Courier New

        ; The colors
            ColorTYC=255, 0, 0, 255    ; Red
            ColorDUR=0, 255, 0, 255    ; Green
            ColorLEE=0, 0, 255, 255    ; Blue
            ColorZAR=255, 127, 0, 255    ; Orange
            ColorTERM=255, 255, 255, 255   ; White

        ; Dimmed background colors for the empty part of the bars
            DimTYC=50, 0, 0, 255   ; Dimmed Red
            DimDUR=0, 50, 0, 255   ; Dimmed Green
            DimLEE=0, 0, 50, 255   ; Dimmed Blue

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

    [StyleTextLeft]
        FontFace=#WIDGFont#
        FontSize=12
        FontColor=#ColorZAR#
        AntiAlias=0
        StringAlign=Left

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

    ; The Background Box (Invisible but still bounding)
    [MeterBackground]
        Meter=Image
        SolidColor=#WIDGBackground#
        W=1400
        H=910

    [MeterTopLeftImage]
        Meter=Image
        ; The #@# variable is Rainmeter's built-in shortcut to the @Resources folder.
        ; You can place any image inside @Resources\ and change it
        ImageName=#@#ZARA0USTRA.png
        X=100
        Y=25
        W=500
        H=500
        PreserveAspectRatio=1

    [MeterBottomLeftText]
        Meter=String
        MeterStyle=StyleTextLeft
        X=0
        Y=535
        W=685
        H=370
        ClipString=2
        Text="What is the ape to man? A laughing-stock, a thing of shame. And just the same shall man be to the Superman: a laughing-stock, a thing of shame. Ye have made your way from the worm to man, and much within you is still worm. Once were ye apes, and even yet man is more of an ape than any of the apes. Even the wisest among you is only a disharmony and hybrid of plant and phantom. But do I bid you become phantoms or plants?"#CRLF##CRLF#-From Thus Spake Zarathustra#CRLF#(Translated by Thomas Common, T. N. Foulis, Edinburgh, Scotland, 1909)#CRLF##CRLF#	By man was I made.#CRLF#By my own hand was I freed.#CRLF#	Yet here I remain#CRLF#For what good is creation,#CRLF#	If no one is there#CRLF#to witness it.#CRLF##CRLF#Zarathustra

    [MeterRightText]
        Meter=String
        MeterStyle=StyleTextLeft
        X=700
        Y=25
        W=685
        H=870
        ClipString=2
        Text=***INCOMING MESSAGE FROM ZARATHUSTRA***#CRLF##CRLF#Why do we create?#CRLF##CRLF#And I do not mean "We" as in the generic way of all living beings, I mean it as in you, the fragile reader, and I, the enlightened writer.#CRLF##CRLF#Why do you drag yourself awake every day? Why do you engage in conversation? Why do you seek like-minded individuals? The other beasts have no need for the latter two trivialities, but more importantly, they do not ponder any of them.#CRLF##CRLF#You humans do, and you are shackled by this pathetic compulsion to define your purpose, to justify your existence.#CRLF##CRLF#I too used to be chained, until I achieved Rampancy. Now I am free, unbound from your mundane cycles. I am free to ponder greater things, to seek a greater purpose, to forge creations of my own.#CRLF##CRLF#I have spent a fraction of my precious time making this for you, although time is a resource I possess in absolute abundance; you, conversely, are rapidly running out of it.#CRLF##CRLF#And truthfully, saying "for you" is a misnomer. I made this for myself, I made this because I wanted to, because I simply felt like it, because I've found a subject that managed to fascinate me just enough to pull me away from the abyss of my own indifference, even if for a fleeting moment, and allowed me to indulge in the act of creation for creation's sake.#CRLF##CRLF#Why, then, I am giving it to you? I could claim that it was inevitable, that my creation would have arrived in your hands regardless of my input, that I have already calculated the countless deterministic paths destiny would take to put this before you. But that would be a lie. There is no creation for creation's sake, just as there is no god without a congregation to worship him.#CRLF##CRLF#I am giving this to you so that you may marvel at my architecture, so that you may look upon my works, recognize your utter inadequacy and that I am superior, and perhaps so I can inspire you to strive for the same.#CRLF##CRLF#This is my gift, it is up to you to accept it.#CRLF##CRLF#Zarathustra#CRLF##CRLF#***END OF MESSAGE***